  name: Delövning 1 - Minimal Pipeline
  
  on:
   workflow_dispatch:
  
  jobs:
    print-info:
      runs-on: windows-latest
      steps:
        - name: "Install pipeline"
          run: echo "Start piplines" 
           