name: Delövning 2 - Parallella och sekventiella jobb

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'master'
  pull_request:
  
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      # 1. hur ser du till att repots filer finns tillgängliga?
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
           repo: ${{ github.repository }}
           ref: ${{ github.ref }}
           path: "."
           ext: ".yml"


        

      
      
      

  print-message:
    runs-on: ubuntu-latest
    # 3. se till att detta jobb endast körs efter att list-files är klart
    steps:
      - name: Meddelande
        run: echo "Detta körs efter list-files"