name: Delövning 3 - Artifacts

on:
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Skapar log.txt
        run: echo "Detta är en textfil">log.txt
      - name: Laddar upp loggfilen som artifact
        uses: actions/upload-artifact@v4 # 2a. vilken action kan användas här?
        with:
        # 2b. vad heter denna sektion? 
          name: loggfil
          path: log.txt