name: Delövning 4 - Triggers

on:
  
  push:      # 1. Triggar vid commit (push)
  pull_request:  # 2. Triggar vid pull request

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo trigger info        
        run: |
          echo "Workflow triggas av:{{ github.event_name}} "
          echo "Gren: ${{ github.ref }}"